### ISSUE TITLE
Source-version inference picks too-old compiler for Vyper ERC20 example

### ISSUE THREAD

**Issue by charles-cooper** [vyperlang/vyupgrade#3]
_co-authored by gpt-5.5_

## Repro

Using the public Vyper ERC20 example from `vyperlang/vyper` `master`:

```bash
curl -L -o ERC20.vy \
  https://raw.githubusercontent.com/vyperlang/vyper/master/examples/tokens/ERC20.vy

uvx --from git+https://github.com/vyperlang/vyupgrade \
  vyupgrade --check ERC20.vy
```

Observed with `vyupgrade 0.4.1`:

```text
vyupgrade 0.4.1
source: inferred per file
target: 0.4.3

ERC20.vy
  VY001 modernized version pragma (line 1)
  source compile: failed
  source error:
    vyper.exceptions.VyperException: Compilation failed with the following errors:

    ArgumentException: Invalid argument count for call to 'Transfer': expected 3, got 0
      ... log IERC20.Transfer(sender=..., receiver=..., value=...)

    ArgumentException: Invalid argument count for call to 'Approval': expected 3, got 0
      ... log IERC20.Approval(owner=..., spender=..., value=...)

  target compile: passed
```

The same file compiles with Vyper `0.4.1+`:

```bash
uvx --from vyper==0.4.0 vyper ERC20.vy  # fails with the event argument errors above
uvx --from vyper==0.4.1 vyper ERC20.vy  # passes
uvx --from vyper==0.4.3 vyper ERC20.vy  # passes
```

And `vyupgrade` passes source/target validation when the source version is specified explicitly:

```bash
uvx --from git+https://github.com/vyperlang/vyupgrade \
  vyupgrade --check --source-version 0.4.3 --target-version 0.4.3 ERC20.vy
```

## Expected

For a file with a broad pragma like:

```vyper
#pragma version >0.3.10
```

`vyupgrade` should either:

1. infer a source compiler version that can compile the current source, or
2. make the source-version inference failure explicit enough that users know to pass `--source-version 0.4.1` or newer.

Right now the output says only `source: inferred per file`, and the compiler error looks like the contract is invalid even though it compiles under newer compatible Vyper versions.

**Comment by charles-cooper** [comment]
i think in this case `vyupgrade` should actually just not do anything besides strip the version pragma?

**Comment by charles-cooper** [comment]
_co-authored by gpt-5.5_

I think yes: for inferred source compilers under a broad pragma, we should prefer the newest compiler satisfying both the source pragma and the requested target, not the floor.

Proposed split:

```text
rule gating:      minimum satisfying version  # did this migration cross X?
source validate:  newest satisfying version <= target version
```

So for `#pragma version >0.3.10` targeting `0.4.3`, source validation should use `0.4.3`, while rule gating can still treat the source floor as `0.4.0`.

I would not use the absolute highest known compiler, because known versions may include opt-in alphas like `0.5.0a*`. Bound it by the requested target unless the user explicitly targets/specifies an alpha.

Expected result for the ERC20 example: compile source with `0.4.3`, apply only `VY001` for the pragma, and avoid the false source compile failure from `0.4.0`.
